[package]
name = "speak"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/blyxyas/speak/"
keywords = [
	"speak",
	"machine-learning",
	"nlp",
	"natural-language-processing",
	"conversation",
	"minimal",
	"fast",
]
license = "GNU General Public License v2.0"
description = "A minimal, fast, machine-learning based chatbot"
publish = false

[dependencies]
aquamarine = { version = "0.1.1", optional = true }
rand = "0.8.5"


# Now, we add the lib section just for the testing

# Dev dependencies
[dev-dependencies]
colored = "2.0.0"

[lib]
name = "speak"
bench = true
doc = true
edition = "2021"
crate-type = ["lib"]

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./extra/docs/katex-header.html"]

[features]
# debug is required (being that Speak is in development)
default = ["debug", "fancy_docs"]
fancy_docs = ["dep:aquamarine"]
debug = []
