[package]
name = "speak"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/blyxyas/speak/"
keywords = ["speak", "machine-learning", "nlp", "natural-language-processing", "conversation", "minimal", "fast", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"