[package]
name = "speak"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/blyxyas/speak/"
keywords = ["speak", "machine-learning", "nlp", "natural-language-processing", "conversation", "minimal", "fast", "cli"]
license = "GNU General Public License v2.0"
description = "A minimal, fast, machine-learning based chatbot"
publish = false

[dependencies]

<<<<<<< HEAD
[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./extra/docs/katex-header.html" ]
=======
# [package.metadata.docs.rs]
# rustdoc-args = [ "--html-in-header", "./extra/docs/katex-header.html" ]
>>>>>>> algorithm
